### PR TITLE
HERITAGE-204 Build secondary navigation for data-visualisation options

### PR DESCRIPTION
**Pull request by garethmead**
Ticket URL: [HERITAGE-204](https://national-archives.atlassian.net/browse/HERITAGE-204)

## About these changes

Built secondary navigation displaying List, Map, Timeline and Tag views

## How to check these changes

This menu can be seen on the catalogue search page `/search/catalogue/`. Styles have been added for all breakpoints

## Before assigning to reviewer, please make sure you have

- [x] Checked things thoroughly before handing over to reviewer
- [x] Checked PR title starts with ticket number as per project conventions to help us keep track of changes
- [x] Ensured that PR includes only commits relevant to the ticket
- [x] Waited for all CI jobs to pass before requesting a review
- [ ] Added/updated tests and documentation where relevant

## Merging PR guidance

Follow [docs\developer-guide\contributing.md](https://nationalarchives.github.io/ds-wagtail/developer-guide/contributing/)

## Deployment guidance

Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds-wagtail/infra/environments/)

[HERITAGE-204]: https://national-archives.atlassian.net/browse/HERITAGE-204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by TNA-Allan — COMMENTED** [review]
@garethmead 

I'm not able to view the new icons on my local run, and getting 
Failed to load resource: the server responded with a status of 404 (Not Found)
HERITAGE-204-icons

There are 4 png's for this ticket. 
I've downloaded them from the ticket and placed them under templates/static/images/
run fab dev -> build

1) How can I get these png's to show, unless this would be an issue with my local settings.  In that case I should resolve them independent from this ticket. 
2) Should these png's be part of the PR
3) Not sure if this is anything to do with these [lines](https://github.com/nationalarchives/ds-ohos-wagtail/blob/develop/.gitignore#L15-L19)  .gitingnore

**Comment by garethmead** [comment]
> @garethmead
> 
> I'm not able to view the new icons on my local run, and getting Failed to load resource: the server responded with a status of 404 (Not Found) HERITAGE-204-icons
> 
> There are 4 png's for this ticket. I've downloaded them from the ticket and placed them under templates/static/images/ run fab dev -> build
> 
> 1. How can I get these png's to show, unless this would be an issue with my local settings.  In that case I should resolve them independent from this ticket.
> 2. Should these png's be part of the PR
> 3. Not sure if this is anything to do with these [lines](https://github.com/nationalarchives/ds-ohos-wagtail/blob/develop/.gitignore#L15-L19)  .gitingnore

The icons used for this are using the font awesome font used by other icons on the site https://fontawesome.com/search?q=pin&o=r&s=solid&f=classic, so no additional images should be required here. That is brought in by tna-frontend https://github.com/nationalarchives/tna-frontend/blob/main/src/nationalarchives/lib/font-awesome/fontawesome.scss to try and keep things consistent with other areas of the project. Are you able to see any other icons on the site?

A potential fix might be to remove your `node_modules` directory and then trying to run `run fab dev -> build` again

**Review by TNA-Allan — APPROVED** [review]
> The icons used for this are using the font awesome font used by other icons on the site https://fontawesome.com/search?q=pin&o=r&s=solid&f=classic, so no additional images should be required here. That is brought in by tna-frontend https://github.com/nationalarchives/tna-frontend/blob/main/src/nationalarchives/lib/font-awesome/fontawesome.scss to try and keep things consistent with other areas of the project. Are you able to see any other icons on the site?
> A potential fix might be to remove your node_modules directory and then trying to run run fab dev -> build again

Thanks for the explanation.

I'm not able to view other icons as well - Home Page. I tried the potential fix but its the same issue on my machine.

Approving from BE template changes perspective. _Also as the icons on home page do show up on the hosted site, I would image these would too._

**Review by JohnHeeryTNA — APPROVED** [review]
Approving changes from FE perspective.

**Pull request merged**
