### PR TITLE
HERITAGE-51 Restyle Search block from Etna to OHOS

### PR DESCRIPTION
**Pull request by garethmead**
Ticket URL: [HERITAGE-51](https://national-archives.atlassian.net/browse/HERITAGE-51)

## About these changes

Updates homepage and and search page search blocks to use updated style

Note: The orange button colour was included in `HERITAGE-55` and won't be reflected in the changes here until that's merged

## How to check these changes

View the homepage or search page to observe style changes to the search bar

## Before assigning to reviewer, please make sure you have

- [x] Checked things thoroughly before handing over to reviewer
- [x] Checked PR title starts with ticket number as per project conventions to help us keep track of changes
- [x] Ensured that PR includes only commits relevant to the ticket
- [x] Waited for all CI jobs to pass before requesting a review
- [ ] Added/updated tests and documentation where relevant

## Merging PR guidance

Follow [docs\developer-guide\contributing.md](https://nationalarchives.github.io/ds-wagtail/developer-guide/contributing/)

## Deployment guidance

Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds-wagtail/infra/environments/)

[HERITAGE-51]: https://national-archives.atlassian.net/browse/HERITAGE-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by garethmead** [comment]
@ahosgood It'd be good to get your opinion on consolidating `_search-landing-hero.scss` and `_search-results-hero.scss` as there's a lot of similarity between the 2 files. Any insight into why this might be a bad idea on this project would be useful, as this may have been done for good reason previously

**Comment by ahosgood** [comment]
@garethmead - No reason I can think of not to merge them. It's probably just historical reasons that they are separate. There are loads of duplications that I am also working through on ETNA!

**Review by TNA-Allan — APPROVED** [review]
Tested and looks good to me. Thanks @garethmead

**Comment by garethmead** [comment]
> @garethmead - No reason I can think of not to merge them. It's probably just historical reasons that they are separate. There are loads of duplications that I am also working through on ETNA!

@ahosgood I've done the work to consolidate the search hero styles into a single `_search-hero` partial

**Review by ahosgood — APPROVED** [review]

**Pull request merged**
